import type { Metadata } from "next";
// import { AuthProvider } from '../context/authContext'; // Assuming the path is correct
import "./globals.css";
import AuthProvider from '../context/authContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
