exports.plans = [
  {
    planName: "Free",
    price: 0,
    emailCredit: "Unlimited",
    actualPrice: 0,
    emailCredits: 0,
    mobileCredits: 0,
    per: "Month",
    features: [],
    isCurrentPlan: true,
  },
  {
    planName: "Basic",
    price: 19,
    emailCredit: "Unlimited",
    actualPrice: 19,
    emailCredits: 2000,
    per: "Month",
    mobileCredits: 150,
    features: [],
    isCurrentPlan: false,
  },
  {
    planName: "Professional",
    price: 87,
    emailCredit: "Unlimited",
    actualPrice: 87,
    per: "Month",
    emailCredits: 10000,
    mobileCredits: 500,
    features: [],
    isCurrentPlan: false,
  },
  {
    planName: "Organisation",
    price: 197,
    emailCredit: "Unlimited",
    actualPrice: 197,
    per: "Month",
    emailCredits: 20000,
    mobileCredits: 1000,
    features: [],
    isCurrentPlan: false,
  },
];

exports.annualPlans = [
  {
    planName: "Free",
    price: 0,
    emailCredit: "Unlimited",
    actualPrice: 0,
    emailCredits: 0,
    mobileCredits: 0,
    per: "Month",
    features: [],
    isCurrentPlan: true,
  },
  {
    planName: "Basic",
    price: 182.4,
    emailCredit: "Unlimited",
    actualPrice: 228,
    emailCredits: 24000,
    mobileCredits: 1800,
    per: "Year",
    features: [],
    isCurrentPlan: false,
  },
  {
    planName: "Professional",
    price: 835.2,
    emailCredit: "Unlimited",
    actualPrice: 1044,
    emailCredits: 120000,
    mobileCredits: 6000,
    per: "Year",
    features: [],
    isCurrentPlan: false,
  },
  {
    planName: "Organisation",
    price: 1892.4,
    emailCredit: "Unlimited",
    actualPrice: 2364,
    emailCredits: 240000,
    mobileCredits: 12000,
    per: "Year",
    features: [],
    isCurrentPlan: false,
  },
];
